from airflow import DAG
#from airflow.operators.python import PythonOperator, BranchPythonOperator
from airflow.providers.standard.operators.python import PythonOperator, BranchPythonOperator
#from airflow.operators.bash import BashOperator
from airflow.providers.standard.operators.bash import BashOperator

from random import randint
from datetime import datetime, timedelta

default_args = {
    "owner": "james bensoussan",
    "depends_on_past": False,
    "email": ["james.bensoussan@gmail.com"],
    "email_on_failure": True,
    "retries": 1,
    "retry_delay": timedelta(minutes=2)
}

def _training_model():
    return randint(1,10)

def _choose_best_model(ti):
    # We want to get the best accuracy by defining a threshold 
    # - based on which we are executing a task or another
    # We do that by using the branch python operator
    # How to get the best accuracy among all of those accuracies
    # That's were we need to share some data between our tasks
    # We want to use accuracy generated by the training models tasks into the task choose_best_model
    # The way to do that is by using Xcoms (cross communications message)
    # this is a mechanism to share data between tasks in the DAG
    # The accuracy is pushed and stored into Airflow Database
    # We can then fetch it back by the other Aiflow tasks of the DAG
    # For this purpose we use the task instance object (ti)
    # we have to return the task id of next task we execute by the BranchPythonOperator
    # This pulls the curracy from the database
    accuracies =  ti.xcom_pull(task_ids= ['training_model_A','training_model_B','training_model_C']) 
    best_accuracy = max(accuracies)
    if (best_accuracy > 8):
        return 'accurate'
    return 'inaccurate'

# creating the DAG Object
with DAG("my_dag"
         ,start_date =datetime(2026,9,28)
         ,schedule = "0 1 * * *"
         ,catchup=False
         ,max_active_runs=1
         ,tags=['my_dag'],) as dag:
    
    training_model_A  = PythonOperator(
        # unique identifier of the DAG
        task_id = "training_model_A",
        # python function that we want to call from that task
        python_callable = _training_model
    )

    training_model_B  = PythonOperator(
    # unique identifier of the DAG
    task_id = "training_model_B",
    # python function that we want to call from that task
    python_callable = _training_model
    )

    training_model_C  = PythonOperator(
    # unique identifier of the DAG
    task_id = "training_model_C",
    # python function that we want to call from that task
    python_callable = _training_model
    )

    choose_best_model = BranchPythonOperator(
        task_id ="choose_best_model",
        python_callable = _choose_best_model
    )

    accurate = BashOperator (
        task_id = "accurate",
        bash_command = "echo 'accurate'"
    )

    inaccurate = BashOperator (
        task_id = "inaccurate",
        bash_command = "echo 'inaccurate'"
    )

    # Defining the order of execution of the tasks (dependencies)
    # >> is used to define the order of execution of the downstream tasks
    # << is used to define the order of execution of the upstream tasks
    [training_model_A,training_model_B,training_model_C] >> choose_best_model >> [accurate,inaccurate]
